// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgjsoepspttmtnmgzkzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnanNvZXBzcHR0bXRubWd6a3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODExNzIsImV4cCI6MjA3MDE1NzE3Mn0.DXfi_CvPEfGjSjFIYfUuy4_EYGNIXkmFSMiM68J6VcY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});